PROJECT         := Smoothieware-NG
DEVICES         := NUCLEO_F401RE \
                   LPC1768
GCC4MBED_DIR    := ../gcc4mbed
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1
USER_LIBS       := $(GCC4MBED_DIR)/external/mbed-os/features/unsupported/USBDevice

include $(GCC4MBED_DIR)/build/gcc4mbed.mk

